---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespaces-configurations
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/romerobu/gitops-cluster-management.git
      revision: main
      files:
      - path: "cluster-definition/**/cluster.json"
  template:
    metadata:
      name: '{{cluster.lowercase_name}}-namespaces'
    spec:
      project: default
      source:
        repoURL: https://github.com/romerobu/gitops-cluster-management.git
        targetRevision: main
        path: cluster-config/components/namespaces/overlays/{{cluster.name}}
      destination:
        server: '{{cluster.address}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
