---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config-as
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/romerobu/gitops-cluster-management.git
      revision: hub-cluster
      files:
      - path: "cluster-definition/HUB-CLUSTER/cluster.json"
  template:
    metadata:
      name: 'bootstrapped-cluster-config'
    spec:
      project: default
      source:
        repoURL: https://github.com/romerobu/gitops-cluster-management.git
        targetRevision: main
        path: cluster-config/cluster-config-as
      destination:
        server: '{{cluster.address}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
